name: Deploy to ArgoCD
on:
  workflow_dispatch: 
     

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: clowdhaus/argo-cd-action/@main
      env:
    # Only required for first step in job where API is called
    # All subsequent setps in a job will not re-download the CLI
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       command: version
       options: --client
    - uses: clowdhaus/argo-cd-action/@main
  # CLI has already been downloaded in prior step, no call to GitHub API
      with:
        command: version
        options: --client
    - name: Create or Update ArgoCD Application
      run: |
          argocd app create my-app \
            --project default
            --repo https://github.com/vignesh-vicky-tech/repo14.git \
            --path yaml-files \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace default 
    - name: Sync app
      run: |
          argocd app sync my-app
