name: Deploy to ArgoCD
on:
  workflow_dispatch: 
     

jobs:
  deploy:
    runs-on: ubuntu-latest

    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up ArgoCD CLI
        uses: clowdhaus/argo-cd-action/@main
        with:
          server: ${{ secrets.ARGOCD_SERVER }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          insecure: true

      # - name: Set up Kubernetes Config
      #   run: echo ${{ secrets.KUBECONFIG }} | base64 -d > kubeconfig
      #   shell: bash

      
        
      # - name: Create or Update ArgoCD Application
      #   run: |
      #     argocd app create my-app \
      #       --repo https://github.com/yourusername/your-repo.git \
      #       --path path/to/application \
      #       --dest-server https://kubernetes.default.svc \
      #       --dest-namespace my-namespace \
      #       --upsert
      #   env:
      #     KUBECONFIG: kubeconfig


  #   - uses: clowdhaus/argo-cd-action/@main
  #     env:
  #   # Only required for first step in job where API is called
  #   # All subsequent setps in a job will not re-download the CLI
  #       GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  #     with:
  #      command: version
  #      options: --client
  #   - uses: clowdhaus/argo-cd-action/@main
  # # CLI has already been downloaded in prior step, no call to GitHub API
  #     with:
  #       command: version
  #       options: --client
         
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with: 
          args: get pods

      - name: Apply ArgoCD Application Manifest
        run: |
          kubectl apply -f https://github.com/vignesh-vicky-tech/argocd-apply.git
      
      # - name: ArgoCD Login
         
      #   run: |
      #     argocd login 172.30.46.16:32145 --username admin --password OJjZ1gAeWCh4tjC0
        
      # - name: Create or Update ArgoCD Application
      #   run: |
      #     argocd app create my-app \
      #       --project default
      #       --repo https://github.com/vignesh-vicky-tech/repo14.git \
      #       --path yaml-files \
      #       --dest-server https://kubernetes.default.svc \
      #       --dest-namespace default 
      # - name: Sync app
      #   run: |
      #     argocd app sync my-app
